color0 #12131c
color1 #ffb4ab
color2 #72d2ff
color3 #8dcff1
color4 #bdc2ff
color5 #72d2ff
color6 #8dcff1
color7 #e3e1ef
color8 #8e8fa6
color9 #ffb4ab
color10 #72d2ff
color11 #8dcff1
color12 #bdc2ff
color13 #72d2ff
color14 #8dcff1
color15 #e3e1ef

cursor                #e3e1ef
cursor_text_color     #12131c
background            #12131c
foreground            #e3e1ef
selection_foreground  #c4c4dd
selection_background  #444559
active_border_color   #72d2ff
inactive_border_color #444559
url_color             #72d2ff

active_tab_foreground   #003548
active_tab_background   #72d2ff
inactive_tab_foreground #c4c4dd
inactive_tab_background #444559
cursor_trail_color      #c4c4dd
